# Generated by Django 6.0.3 on 2026-03-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='location',
            name='cidade',
            field=models.CharField(default='Recife', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='consumo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
