# Generated by Django 6.0.3 on 2026-03-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_location_criado_em_location_cidade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
