# Generated by Django 6.0.3 on 2026-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='consumo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ponto',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
