# Generated by Django 6.0.3 on 2026-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ponto_consumo_ponto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='nome',
            field=models.CharField(default='Posto Sem Nome', max_length=100),
        ),
    ]
